baseURL = "http://sawicz.io"
languageCode = "en-us"
title = "Pawel Sawicz"
description = "Tech, Cloud, Infrastructure"
publishDir = "docs"
themesDir = "themes"
theme = "kube"
relativeURLs = true
paginate = 5
googleAnalytics = "UA-123-45"
disqusShortname = "helbards"

[Params]
  RSSLink = "/index.xml"
  author = "Pawel Sawicz"
  github = "pawelsawicz"
  twitter = "sawiczpawel"
  email = "pawel@sawicz.eu"
  popular = false

[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"