baseURL = "https://pawelsawicz.github.io/"
languageCode = "en-us"
title = "Pawel Sawicz on Software"
description = "Pawel Sawicz on Software"
publishDir = "docs"
themesDir = "themes"
theme = "kube"
relativeURLs = true
paginate = 5
googleAnalytics = "UA-123-45"
disqusShortname = "helbards"
aliases = [
    "blog/oredev-videos-are-live/",
    "/oredev-videos-are-live/"
]

[Params]
  RSSLink = "/index.xml"
  author = "Pawel Sawicz"
  github = "pawelsawicz"
  twitter = "sawiczpawel"
  email = "pawel@sawicz.eu"
  popular = false

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Blog"
    weight = -100
    url = "/blog/"
[[menu.main]]
    name = "Faq"
    weight = -100
    url = "/faq/"